In [1]:
import pandas as pd

summary_df = pd.read_csv('../data/vessel_summary.csv')
identities_df = pd.read_csv('../data/vessel_identities.csv')

In [2]:
identities_df['flag'].value_counts()

flag
PAN    24
MHL    20
RUS    17
LBR    16
CMR    11
MLT     6
SLE     6
GRC     5
BRB     5
MDG     4
HKG     4
GIN     3
COM     3
BHS     3
PLW     3
SGP     3
NIC     2
GNQ     2
DEU     2
AZE     2
CHN     2
TUR     2
KWT     1
IMN     1
FRA     1
COK     1
BES     1
MOZ     1
ITA     1
VUT     1
SMR     1
DNK     1
ESP     1
CYM     1
CYP     1
ATG     1
SAU     1
SYR     1
Name: count, dtype: int64

In [3]:
flag_changes = identities_df.groupby('imo')['flag'].nunique().reset_index()
flag_changes.columns = ['imo', 'num_flags']
flag_changes = flag_changes.merge(summary_df[['imo', 'current_name']], on='imo')
flag_changes = flag_changes.sort_values('num_flags', ascending=False)
flag_changes.head(10)

        imo  num_flags         current_name
8   9282481          8        BRITISHGANNET
3   9213296          7       SEAWAYSSHIRLEY
6   9236248          7         MINERVAZENIA
10  9292199          6  BESIKTASDARDANELLES
17  9328170          6               WAFRAH
9   9290373          6    BESIKTASBOSPHORUS
29  9412452          6      UNITEDFORTITUDE
5   9233777          5           BACALIAROS
11  9296377          5          TOKYOSPIRIT
0   9037123          5      ZHONGGANGDALIAN

In [4]:
top_imo = flag_changes.head(5)['imo'].tolist()
cols = ['imo', 'shipname', 'flag', 'transmission_from', 'transmission_to']
timeline = (
    identities_df[identities_df['imo'].isin(top_imo)][cols]
    .sort_values(['imo', 'transmission_from'])
)
timeline['transmission_from'] = pd.to_datetime(timeline['transmission_from'], format='mixed')
timeline['days_since_last_update'] = timeline.groupby('imo')['transmission_from'].diff()
timeline

,imo,shipname,flag,transmission_from,transmission_to,days_since_last_update
65,9213296,SEAWAYSSHIRLEY,MHL,2017-10-02 21:34:28+00:00,2018-11-01T14:10:29Z,NaT
63,9213296,US SHIRLEY,COM,2018-11-02 02:54:00+00:00,2018-12-01T07:41:09Z,395 days 05:19:32
62,9213296,SHIRLEY,LBR,2018-12-01 07:58:07+00:00,2019-06-12T23:58:13Z,29 days 05:04:07
60,9213296,BRIGHTSONIA,PAN,2019-05-18 08:39:13+00:00,2024-10-02T11:38:42Z,168 days 00:41:06
66,9213296,TELESTO,GIN,2024-10-02 12:46:42+00:00,2025-01-09T03:24:35Z,1964 days 04:07:29
64,9213296,TELESTO,BRB,2025-01-09 03:28:03+00:00,2025-11-22T10:48:56Z,98 days 14:41:21
61,9213296,TELESTO,PLW,2025-11-22 20:29:06+00:00,2026-08-15T23:51:19Z,317 days 17:01:03
16,9236248,MINERVAZENIA,GRC,2021-01-04 05:31:34+00:00,2022-08-07T16:03:06Z,NaT
15,9236248,PHOENIX1,COK,2024-10-09 07:58:03+00:00,2025-03-20T10:48:28Z,1374 days 02:26:29
17,9236248,FENGHUANG,BES,2025-03-20 10:49:25+00:00,2025-05-06T11:01:16Z,162 days 02:51:22
19,9236248,FENGHUANG,COM,2025-05-06 11:06:09+00:00,2026-01-07T05:40:18Z,47 days 00:16:44
18,9236248,FENGHUANG,MDG,2026-01-07 05:36:59+00:00,2026-03-04T16:56:24Z,245 days 18:30:50
21,9236248,FENGHUANG,CMR,2026-03-04 17:08:23+00:00,2026-03-23T08:40:01Z,56 days 11:31:24
20,9236248,FENGHUANG,MOZ,2026-03-23 08:45:55+00:00,2026-08-15T23:59:05Z,18 days 15:37:32
7,9282481,BRITISHGANNET,IMN,2012-01-13 03:59:15+00:00,2018-12-12T13:10:10Z,NaT
12,9282481,FRENCH NAVY WARSHIP,FRA,2012-03-13 17:13:44+00:00,2012-03-21T06:01:13Z,60 days 13:14:29
14,9282481,PIPER,MHL,2018-12-12 13:16:50+00:00,2023-02-04T23:21:30Z,2464 days 20:03:06
11,9282481,PRIAPUS,NIC,2023-04-03 12:56:44+00:00,2023-06-11T06:36:00Z,1572 days 23:39:54
8,9282481,TAGOR,PAN,2024-07-06 08:23:17+00:00,2025-09-12T05:12:57Z,459 days 19:26:33
9,9282481,TAGOR,GIN,2025-09-15 11:54:24+00:00,2026-03-17T05:41:01Z,436 days 03:31:07
13,9282481,TAGOR,MDG,2026-03-17 05:45:02+00:00,2026-05-26T08:33:12Z,182 days 17:50:38
10,9282481,TAGOR,CMR,2026-05-26 10:02:57+00:00,2026-08-15T08:39:18Z,70 days 04:17:55
137,9292199,BESIKTASDARDANELLES,TUR,2012-01-03 09:28:28+00:00,2018-08-14T14:55:36Z,NaT
141,9292199,BESIKTAS DARDANELLES,MLT,2018-08-15 12:13:15+00:00,2022-06-10T03:44:00.92Z,2416 days 02:44:47
140,9292199,BESIKTAS DARDANELLES,MHL,2022-06-10 03:49:19+00:00,2023-08-29T13:23:32Z,1394 days 15:36:04
138,9292199,BESIKTAS DARDANELLES,LBR,2023-08-29 17:15:35+00:00,2024-02-23T10:04:11Z,445 days 13:26:16
139,9292199,KAYSERI,PAN,2024-02-23 11:52:55+00:00,2025-12-01T06:57:06Z,177 days 18:37:20
142,9292199,ALTURA,SLE,2025-11-30 10:00:41+00:00,2026-07-20T08:27:10Z,645 days 22:07:46
143,9292199,929-21%-99%,NaN,2025-12-10 22:24:12+00:00,2026-07-24T13:52:52Z,10 days 12:23:31
1,9328170,WAFRAH,KWT,2012-01-08 14:12:44+00:00,2022-05-10T11:17:25Z,NaT
4,9328170,LILA FUJAIRAH,LBR,2022-05-10 11:31:35.730000+00:00,2023-02-18T05:12:21Z,3774 days 21:18:51.730000
0,9328170,AETHER,PAN,2023-01-23 14:38:25+00:00,2025-10-06T11:09:01Z,258 days 03:06:49.270000
5,9328170,AETHER,GIN,2025-10-06 11:17:25+00:00,2026-03-14T15:49:37Z,986 days 20:39:00
2,9328170,AETHER,MDG,2026-03-14 15:43:17+00:00,2026-05-19T14:51:02Z,159 days 04:25:52
6,9328170,AETHER,CMR,2026-05-19 14:56:47+00:00,2026-05-20T07:55:53Z,65 days 23:13:30
3,9328170,AETHER,CMR,2026-05-20 08:24:58+00:00,2026-08-15T23:58:03Z,0 days 17:28:11