  Vessel Flag Change Frequency Analysis (Pre- vs. Post-2023)

In [1]:
import pandas as pd
from requests import head

summary_df = pd.read_csv('../data/vessel_summary.csv')
identities_df = pd.read_csv('../data/vessel_identities.csv')

In [2]:
ais_df = identities_df[identities_df['source'] == 'self_reported'].copy()

ais_df['transmission_from'] = pd.to_datetime(
    ais_df['transmission_from'], format='mixed', utc=True
)
ais_df['transmission_to'] = pd.to_datetime(
    ais_df['transmission_to'], format='mixed', utc=True
)

In [3]:
# Standardize ship names (clean non-breaking spaces and irregular whitespace)
identities_df['shipname'] = (
    identities_df['shipname']
    .astype(str)
    .str.replace('\xa0', ' ')
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

Most popular flags:

In [4]:
identities_df['flag'].value_counts()

flag
PAN    33
MHL    32
RUS    32
LBR    25
MLT    13
GRC    12
CMR    11
SLE     7
HKG     6
SGP     6
BHS     5
BRB     5
MDG     4
GIN     4
PLW     4
AZE     4
CHN     4
TUR     4
COM     3
KWT     2
GBR     2
NIC     2
COK     2
ITA     2
GNQ     2
CYP     2
CAN     2
DNK     2
CYM     2
DEU     2
SAU     2
IMN     1
FRA     1
BES     1
MOZ     1
VUT     1
SMR     1
ESP     1
ATG     1
SYR     1
Name: count, dtype: int64

In [5]:
#Ships(imo) who changed the flag the most
flag_changes = identities_df.groupby('imo')['flag'].nunique().reset_index()
flag_changes.columns = ['imo', 'num_flags']
flag_changes = flag_changes.merge(summary_df[['imo', 'current_name']], on='imo')
flag_changes = flag_changes.sort_values('num_flags', ascending=False)
flag_changes.head(10)

        imo  num_flags current_name
8   9282481          9        TAGOR
3   9213296          8      TELESTO
6   9236248          8    FENGHUANG
9   9290373          7      RAVELIN
5   9233777          6     OCEAN II
17  9328170          6       AETHER
11  9296377          6     MARJORIE
10  9292199          6  929-21%-99%
29  9412452          6      TSOIZIT
4   9224453          5       TRACOS

 Intelligence:look at the flag-change patterns for the top 5 most "suspicious" vessels before calculating the metric for the entire fleet.

In [6]:
top_imo = flag_changes.head(5)['imo'].tolist()
cols = ['imo', 'shipname', 'flag', 'transmission_from', 'transmission_to']
timeline = (
    identities_df[identities_df['imo'].isin(top_imo)][cols]
    .sort_values(['imo', 'transmission_from'])
)
timeline['transmission_from'] = pd.to_datetime(timeline['transmission_from'], format='mixed')
timeline['days_since_last_update'] = timeline.groupby('imo')['transmission_from'].diff()
timeline

,imo,shipname,flag,transmission_from,transmission_to,days_since_last_update
97,9213296,OVERSEAS SHIRLEY,CAN,2012-01-02 16:53:24+00:00,2012-10-09T14:54:10Z,NaT
96,9213296,OVERSEAS SHIRLEY,MHL,2012-10-23 05:49:54+00:00,2019-04-13T06:06:08Z,294 days 12:56:30
95,9213296,SEAWAYSSHIRLEY,MHL,2017-10-02 21:34:28+00:00,2018-11-01T14:10:29Z,1805 days 15:44:34
100,9213296,US SHIRLEY,COM,2018-11-02 02:54:00+00:00,2018-12-01T07:41:09Z,395 days 05:19:32
98,9213296,SHIRLEY,LBR,2018-12-01 07:58:07+00:00,2019-06-12T23:58:13Z,29 days 05:04:07
103,9213296,BRIGHT SONIA,PAN,2019-05-18 08:18:21+00:00,2024-10-02T12:45:54Z,168 days 00:20:14
102,9213296,BRIGHTSONIA,PAN,2019-05-18 08:39:13+00:00,2024-10-02T11:38:42Z,0 days 00:20:52
94,9213296,TELESTO,GIN,2024-10-02 12:46:42+00:00,2025-01-09T03:24:35Z,1964 days 04:07:29
99,9213296,TELESTO,BRB,2025-01-09 03:28:03+00:00,2025-11-22T10:48:56Z,98 days 14:41:21
101,9213296,TELESTO,PLW,2025-11-22 20:29:06+00:00,2026-09-08T19:47:29Z,317 days 17:01:03
149,9233777,CAPE BOWEN,MHL,2012-01-05 17:54:14+00:00,2015-09-02T07:47:48Z,NaT
148,9233777,BACALIAROS,MHL,2015-09-10 06:59:38+00:00,2020-12-01T14:24:54Z,1343 days 13:05:24
147,9233777,BACALIAROS,DEU,2015-09-11 03:42:50+00:00,2020-12-01T14:20:05Z,0 days 20:43:12
153,9233777,AMETHYST MTS,CYP,2020-12-01 14:42:04+00:00,2023-08-15T21:25:23Z,1908 days 10:59:14
151,9233777,AMETHYST MTS,LBR,2023-08-15 21:51:57+00:00,2024-05-25T01:23:18Z,987 days 07:09:53
150,9233777,OCEAN II,ATG,2024-05-02 17:29:40+00:00,2025-11-12T13:52:44Z,260 days 19:37:43
152,9233777,OCEAN II,CMR,2025-11-12 13:39:47+00:00,2026-09-08T23:55:33Z,558 days 20:10:07
22,9236248,MINERVA ZENIA,GRC,2012-01-01 00:29:53+00:00,2020-10-24T00:55:16Z,NaT
23,9236248,MINERVA ZENIA,GRC,2017-08-07 04:11:28+00:00,2020-05-28T07:53:04Z,2045 days 03:41:35
20,9236248,PHOENIX I,PAN,2020-10-24 21:52:09+00:00,2025-02-03T03:02:03Z,1174 days 17:40:41
19,9236248,MINERVAZENIA,GRC,2021-01-04 05:31:34+00:00,2022-08-07T16:03:06Z,71 days 07:39:25
21,9236248,PHOENIXI,PAN,2021-11-29 15:03:04.640000+00:00,2021-12-11T04:09:23.3Z,329 days 09:31:30.640000
24,9236248,PHOENIX1,COK,2024-10-09 07:58:03+00:00,2025-03-20T10:48:28Z,1044 days 16:54:58.360000
25,9236248,PHOENIX I,COK,2024-10-09 07:59:23+00:00,2025-03-20T10:45:27Z,0 days 00:01:20
26,9236248,FENGHUANG,BES,2025-03-20 10:49:25+00:00,2025-05-06T11:01:16Z,162 days 02:50:02
28,9236248,FENGHUANG,COM,2025-05-06 11:06:09+00:00,2026-01-07T05:40:18Z,47 days 00:16:44
29,9236248,FENGHUANG,MDG,2026-01-07 05:36:59+00:00,2026-03-04T16:56:24Z,245 days 18:30:50
27,9236248,FENGHUANG,CMR,2026-03-04 17:08:23+00:00,2026-03-23T08:40:01Z,56 days 11:31:24
30,9236248,FENGHUANG,MOZ,2026-03-23 08:45:55+00:00,2026-09-06T19:21:27Z,18 days 15:37:32
10,9282481,BRITISH GANNET,GBR,2012-01-04 17:14:53+00:00,2018-12-12T13:07:00Z,NaT
9,9282481,BRITISHGANNET,IMN,2012-01-13 03:59:15+00:00,2018-12-12T13:10:10Z,8 days 10:44:22
14,9282481,FRENCH NAVY WARSHIP,FRA,2012-03-13 17:13:44+00:00,2012-03-21T06:01:13Z,60 days 13:14:29
13,9282481,PIPER,MHL,2018-12-12 13:16:50+00:00,2023-02-04T23:21:30Z,2464 days 20:03:06
12,9282481,TAGOR,PAN,2023-01-18 01:58:22+00:00,2025-09-22T06:28:48Z,1497 days 12:41:32
18,9282481,PRIAPUS,NIC,2023-04-03 12:56:44+00:00,2023-06-11T06:36:00Z,75 days 10:58:22
11,9282481,TAGOR,PAN,2024-07-06 08:23:17+00:00,2025-09-12T05:12:57Z,459 days 19:26:33
16,9282481,TAGOR,GIN,2025-09-15 11:54:24+00:00,2026-03-17T05:41:01Z,436 days 03:31:07
15,9282481,TAGOR,MDG,2026-03-17 05:45:02+00:00,2026-05-26T08:33:12Z,182 days 17:50:38
17,9282481,TAGOR,CMR,2026-05-26 10:02:57+00:00,2026-08-15T08:39:18Z,70 days 04:17:55
227,9290373,BESIKTAS BOSPHORUS,TUR,2012-01-01 00:16:38+00:00,2018-08-03T12:15:04Z,NaT
226,9290373,BESIKTASBOSPHORUS,TUR,2012-01-01 00:19:55+00:00,2018-08-03T12:16:09Z,0 days 00:03:17
232,9290373,BESIKTAS BOSPHORUS,MLT,2018-08-03 12:25:39+00:00,2022-04-21T11:24:09.5Z,2406 days 12:05:44
231,9290373,BESIKTAS BOSPHORUS,MHL,2022-04-21 11:30:27+00:00,2023-08-14T05:25:30Z,1356 days 23:04:48
233,9290373,BESIKTAS BOSPHORUS,LBR,2023-07-17 08:04:47+00:00,2024-03-15T19:17:43Z,451 days 20:34:20
230,9290373,KONYA,PAN,2024-02-15 18:03:05+00:00,2025-12-03T07:27:02Z,213 days 09:58:18
229,9290373,VELORA,SLE,2025-12-03 07:10:31+00:00,2026-08-17T08:56:11Z,656 days 13:07:26
228,9290373,RAVELIN,RUS,2026-08-17 13:13:28+00:00,2026-09-08T23:59:17Z,257 days 06:02:57

In [7]:
#transform char to datatime
identities_df['transmission_from'] = pd.to_datetime(identities_df['transmission_from'], format='mixed')
identities_df = identities_df.sort_values(['imo', 'transmission_from'])
identities_df

,imo,source,shipname,flag,ssvid,match_fields,transmission_from,transmission_to,is_verified
170,9037123,self_reported,HAI CHANG DA LIAN,CHN,413202420,SEVERAL_FIELDS,2012-01-03 00:56:11+00:00,2015-05-26T10:00:35Z,True
169,9037123,self_reported,SHAN GANG RONG HE,CHN,413366530,SEVERAL_FIELDS,2015-05-26 10:21:35+00:00,2024-07-24T02:20:46Z,True
168,9037123,registry,ZHONGGANGDALIAN,CHN,413366530,REGISTRY,2015-05-26 10:38:39+00:00,2019-12-14T08:37:28Z,True
173,9037123,self_reported,LIAOYINGYU 35669,NaN,415555555,NO_MATCH,2018-12-14 18:03:42+00:00,2022-09-21T08:08:42.25Z,False
172,9037123,self_reported,ZHONG GANG DA LIAN,MHL,538090558,NO_MATCH,2019-12-14 09:12:33+00:00,2021-09-29T22:51:17Z,False
...,...,...,...,...,...,...,...,...,...
234,9867621,self_reported,ARISTOFANIS,MHL,538008714,NO_MATCH,2019-12-10 07:14:52+00:00,2024-09-17T03:01:32Z,False
235,9867621,registry,KHANKENDI,AZE,423543100,REGISTRY,2024-08-23 07:44:30+00:00,2026-07-31T13:30:53Z,True
236,9867621,self_reported,KHANKENDI,AZE,423543100,SEVERAL_FIELDS,2024-08-23 07:44:37+00:00,2026-09-08T23:19:51Z,True
243,9884150,self_reported,SERGEY LVOV,RUS,273295620,NO_MATCH,2021-08-31 10:22:36+00:00,2026-09-08T23:26:26Z,False
242,9884150,self_reported,SERGEY LVOV,RUS,273557764,NO_MATCH,2025-08-03 01:21:41+00:00,2025-08-11T12:19:00Z,False

In [8]:
#Added column to understand time elapsed since last shipname update
identities_df['days_since_last_update'] = identities_df.groupby('imo')['transmission_from'].diff().dt.days
identities_df

,imo,source,shipname,flag,ssvid,match_fields,transmission_from,transmission_to,is_verified,days_since_last_update
170,9037123,self_reported,HAI CHANG DA LIAN,CHN,413202420,SEVERAL_FIELDS,2012-01-03 00:56:11+00:00,2015-05-26T10:00:35Z,True,NaN
169,9037123,self_reported,SHAN GANG RONG HE,CHN,413366530,SEVERAL_FIELDS,2015-05-26 10:21:35+00:00,2024-07-24T02:20:46Z,True,1239.0
168,9037123,registry,ZHONGGANGDALIAN,CHN,413366530,REGISTRY,2015-05-26 10:38:39+00:00,2019-12-14T08:37:28Z,True,0.0
173,9037123,self_reported,LIAOYINGYU 35669,NaN,415555555,NO_MATCH,2018-12-14 18:03:42+00:00,2022-09-21T08:08:42.25Z,False,1298.0
172,9037123,self_reported,ZHONG GANG DA LIAN,MHL,538090558,NO_MATCH,2019-12-14 09:12:33+00:00,2021-09-29T22:51:17Z,False,364.0
...,...,...,...,...,...,...,...,...,...,...
234,9867621,self_reported,ARISTOFANIS,MHL,538008714,NO_MATCH,2019-12-10 07:14:52+00:00,2024-09-17T03:01:32Z,False,NaN
235,9867621,registry,KHANKENDI,AZE,423543100,REGISTRY,2024-08-23 07:44:30+00:00,2026-07-31T13:30:53Z,True,1718.0
236,9867621,self_reported,KHANKENDI,AZE,423543100,SEVERAL_FIELDS,2024-08-23 07:44:37+00:00,2026-09-08T23:19:51Z,True,0.0
243,9884150,self_reported,SERGEY LVOV,RUS,273295620,NO_MATCH,2021-08-31 10:22:36+00:00,2026-09-08T23:26:26Z,False,NaN
242,9884150,self_reported,SERGEY LVOV,RUS,273557764,NO_MATCH,2025-08-03 01:21:41+00:00,2025-08-11T12:19:00Z,False,1432.0

In [9]:
before_2023 = identities_df[identities_df['transmission_from'] < '2023-01-01']
after_2023 = identities_df[identities_df['transmission_from'] >= '2023-01-01']

### CMP Table showing the average number of days before 2023 and in 2023

In [20]:
mean_before = before_2023.groupby('imo')['days_since_last_update'].mean()
mean_after = after_2023.groupby('imo')['days_since_last_update'].mean()
cmp_df = pd.DataFrame({'before': mean_before, 'after': mean_after}).dropna()
cmp_df

              before        after
imo
9037123   725.250000   800.333333
9164718   885.000000  1448.000000
9213296   448.500000   793.000000
9224453  1333.000000   652.500000
9233777  1083.666667   601.666667
9236248   904.750000   224.571429
9274525   799.800000  1283.000000
9282481   844.000000   453.166667
9290373  1254.000000   394.250000
9292199  1270.000000   319.250000
9296377   687.000000   970.250000
9297541  1918.500000   974.000000
9299707  1262.000000   369.750000
9306809     0.000000  1733.333333
9311610     0.000000  2654.500000
9321718  1313.000000   529.500000
9328170  1888.000000   244.666667
9333577     0.000000  4591.000000
9337341     0.000000  4932.000000
9347308  1319.000000  1231.000000
9358412    82.000000  4804.000000
9384564   459.333333   990.500000
9389071  1076.500000  2655.000000
9389083  1556.000000  1690.500000
9402328     3.000000  2532.500000
9408190   252.500000  1518.000000
9408683   421.666667  1849.500000
9412452  1228.500000   715.750000
9419450   593.500000  1387.000000
9430272  1345.000000   826.333333
9436020  1796.000000  2931.000000
9439383  1864.500000   791.500000
9439539     0.000000  1687.000000
9460564  1638.000000  1563.000000
9472634   406.666667  3618.000000
9621596     0.000000  2914.000000
9645035     0.000000  3977.000000

In [12]:
faster = cmp_df[cmp_df['after'] < cmp_df['before']]
print(f"Started changing them more often: {len(faster)} из {len(cmp_df)} ships")

Started changing them more often: 15 из 37 ships

In [13]:
#save dataFrame to cache for visualization
cmp_df.reset_index().to_csv('../data/flag_change_intervals.csv', index=False)
identities_df.to_csv('../data/identities.csv', index=False)

In [16]:
identities_df['source'].value_counts()

source
self_reported    192
registry          57
Name: count, dtype: int64

In [33]:
mean_before = cmp_df['before'].mean()
mean_after = cmp_df['after'].mean()

print(f"Average before 2023: {mean_before:.1f} days")
print(f"Average after  2023: {mean_after:.1f} days")

Average before 2023: 828.6 days
Average after  2023: 1666.2 days

In [60]:
identities_df.groupby('imo')['flag'].nunique()
flags_before = before_2023.groupby('flag')['imo'].nunique()
flags_after = after_2023.groupby('flag')['imo'].nunique()

flags_df = pd.DataFrame({'before':flags_before, 'after':flags_after}).fillna(0).astype(int)
flags_df = flags_df.sort_values(by='after', ascending=False)
flags_df.to_csv('../data/flag_df.csv', index=False)

flags_df

      before  after
flag
PAN        4     23
CMR        0     10
LBR        9      9
RUS       12      9
SLE        1      6
BRB        0      5
MDG        0      4
GIN        0      4
MHL       19      3
HKG        2      3
NIC        0      2
PLW        1      2
COM        1      2
GNQ        0      2
AZE        1      1
ATG        0      1
VUT        0      1
SMR        0      1
BES        0      1
BHS        2      1
COK        0      1
SYR        0      1
MLT        9      1
MOZ        0      1
CHN        2      0
CAN        2      0
IMN        1      0
ITA        1      0
KWT        1      0
DNK        1      0
ESP        1      0
FRA        1      0
CYP        2      0
CYM        1      0
DEU        2      0
GRC        7      0
GBR        2      0
SAU        1      0
SGP        4      0
TUR        2      0