# Where are shadow fleet tankers managed from?

**Question:** In which countries are the ISM managers of the 50 tankers based?

**Why ISM manager:** the registered owner is often a shell company in an offshore
jurisdiction, while the ISM manager is responsible for the ship's daily operation
and safety, so it is closer to the real operator.

In [18]:
import pandas as pd
shadow_FV = pd.read_csv('../data/shadow_fleet_vessels.csv')

In [4]:
shadow_FV[['registered_owner', 'ship_manager', 'ism_manager']].head(10)

,registered_owner,ship_manager,ism_manager
0,UAE. Wrasse Ship Co,UAE. Zulu Ships Management,UAE. Zulu Ships Management
1,UAE. Blaire Charters Ltd,UAE. Zulu Ships Management,UAE. Tarabya Logistics Ltd
2,UAE. Celestial Overseas Co Ltd,UAE. Triviality Shipping Llc,UAE. Triviality Shipping Llc
3,Seychelles. Tika Shipping Ltd,Seychelles. Tika Shipping Ltd,China. Song Hua Jiang Shipmanagement
4,Seychelles. Shiva Shipping Ltd,Seychelles. Shiva Shipping Ltd,Singapore. Crest Maritime Pte Ltd
5,Seychelles. Dava Shipping Ltd,Seychelles. Dava Shipping Ltd,China. Heng Shan Shipmanagement Co
6,Mauritius. Toila Shipping Ltd,Mauritius. Toila Shipping Ltd,China. Heng Shan Shipmanagement Co
7,Mauritius. Maluga Shipping Ltd,Mauritius. Maluga Shipping Ltd,China. Gao You Hu Shipmanagement Co
8,Marshall Islands. Silver Tetra Marine Co,Marshall Islands. Silver Tetra Marine Co,UAE. Tarabya Logistics Ltd
9,Marshall Islands. Pyramid Ventures Co,Marshall Islands. Pyramid Ventures Co,India. Aaruthra Marine Pvt Ltd

In [22]:
#Sorting places for easier comparison
shadow_FV['ism_country'] = shadow_FV['ism_manager'].str.split('.').str[0]

shadow_FV['reg_country'] = shadow_FV['registered_owner'].str.split('.').str[0]

shadow_FV['manager_country'] = shadow_FV['ship_manager'].str.split('.').str[0]

In [50]:
columns = [ 'ism_country', 'reg_country',  'manager_country']
counts = {}
for col in columns:
    counts[col] = shadow_FV[col].value_counts()

comparision_df = pd.DataFrame(counts).fillna(0).astype(int)
comparision_df.sort_values(by = ['reg_country'], ascending = False)

                   ism_country  reg_country  manager_country
Russia                      14           14               14
China                       17           10               11
Marshall Islands             1            7                7
Seychelles                   0            4                3
UAE                          7            3                3
Mauritius                    0            2                2
Liberia                      0            2                2
Azerbaijan                   2            2                2
India                        4            2                2
Turkey                       2            2                2
Antigua & Barbuda            0            1                1
Singapore                    2            1                1
Unknown                      1            0                0

In [47]:
#For how many of the 50 ships is the owner country different from the ISM country?
shadow_FV['owners_ism_mismatch'] =  shadow_FV['reg_country'] != shadow_FV['ism_country']
shadow_FV['owners_ism_mismatch'].head(10)

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: owners_ism_mismatch, dtype: bool

In [46]:
pd.crosstab(shadow_FV['reg_country'], shadow_FV['ism_country'])

ism_country,Azerbaijan,China,India,Marshall Islands,Russia,Singapore,Turkey,UAE,Unknown
reg_country,,,,,,,,,
Antigua & Barbuda,0,1,0,0,0,0,0,0,0
Azerbaijan,2,0,0,0,0,0,0,0,0
China,0,9,0,0,0,0,0,0,1
India,0,0,2,0,0,0,0,0,0
Liberia,0,0,0,0,0,0,0,2,0
Marshall Islands,0,2,2,1,0,0,0,2,0
Mauritius,0,2,0,0,0,0,0,0,0
Russia,0,0,0,0,14,0,0,0,0
Seychelles,0,3,0,0,0,1,0,0,0
Singapore,0,0,0,0,0,1,0,0,0
Turkey,0,0,0,0,0,0,2,0,0
UAE,0,0,0,0,0,0,0,3,0

In [53]:
comparision_df['net'] = comparision_df['ism_country'] - comparision_df['reg_country']
comparision_df.sort_values('net', ascending = False)

                   ism_country  reg_country  manager_country  net
China                       17           10               11    7
UAE                          7            3                3    4
India                        4            2                2    2
Singapore                    2            1                1    1
Unknown                      1            0                0    1
Turkey                       2            2                2    0
Russia                      14           14               14    0
Azerbaijan                   2            2                2    0
Antigua & Barbuda            0            1                1   -1
Liberia                      0            2                2   -2
Mauritius                    0            2                2   -2
Seychelles                   0            4                3   -4
Marshall Islands             1            7                7   -6

In [55]:
shadow_FV.to_csv('../data/shadow_FV.csv', index=False)