In [1]:
import pandas as pd
vesseles = pd.read_csv('../data/shadow_fleet_vessels.csv')

In [2]:
size_DWT = {
    'Handysize':(10000,40000),
    'Aframax':(80000,110000),
    'Suezmax':(120000,200000),
}
vesseles['dwt_min'] = vesseles['tanker_size'].map(lambda s:size_DWT[s][0])
vesseles['dwt_max'] = vesseles['tanker_size'].map(lambda s:size_DWT[s][1])
vesseles['dwt_mid'] = (vesseles['dwt_min'] + vesseles['dwt_max']) / 2

vesseles[['vessel_name','tanker_size', 'dwt_min','dwt_max', 'dwt_mid']]

             vessel_name tanker_size  dwt_min  dwt_max   dwt_mid
0                 Aether     Aframax    80000   110000   95000.0
1                  Tagor     Aframax    80000   110000   95000.0
2              Phoenix I     Aframax    80000   110000   95000.0
3                 Bhilva     Aframax    80000   110000   95000.0
4                   Torx     Suezmax   120000   200000  160000.0
5                 Aura 1     Aframax    80000   110000   95000.0
6                 Balu 6     Aframax    80000   110000   95000.0
7                  Jewel     Aframax    80000   110000   95000.0
8                Guanyin     Aframax    80000   110000   95000.0
9               Marjorie     Suezmax   120000   200000  160000.0
10                Tracos     Suezmax   120000   200000  160000.0
11             Ling Hong     Aframax    80000   110000   95000.0
12                 Samos     Suezmax   120000   200000  160000.0
13                  Bolu     Aframax    80000   110000   95000.0
14           Centurion I     Aframax    80000   110000   95000.0
15               Telesto     Aframax    80000   110000   95000.0
16                Alaric     Aframax    80000   110000   95000.0
17               Nilanga     Aframax    80000   110000   95000.0
18                Searun     Aframax    80000   110000   95000.0
19           Tiger Wings     Aframax    80000   110000   95000.0
20             Zhuo Yuan     Suezmax   120000   200000  160000.0
21               Tango 2     Aframax    80000   110000   95000.0
22               Tiger 6     Aframax    80000   110000   95000.0
23              Sara Sky     Aframax    80000   110000   95000.0
24               Oceanid     Aframax    80000   110000   95000.0
25              Ocean Ii     Suezmax   120000   200000  160000.0
26                Lachin   Handysize    10000    40000   25000.0
27                   Lxh     Suezmax   120000   200000  160000.0
28          Cc Innovator   Handysize    10000    40000   25000.0
29           As Calcutta   Handysize    10000    40000   25000.0
30               Jin Hui   Handysize    10000    40000   25000.0
31                  Zale     Suezmax   120000   200000  160000.0
32               Arktida   Handysize    10000    40000   25000.0
33        Vasily Surikov   Handysize    10000    40000   25000.0
34   Professor Malyshkin   Handysize    10000    40000   25000.0
35                 Thoth   Handysize    10000    40000   25000.0
36            Midvolga-3   Handysize    10000    40000   25000.0
37               Antares   Handysize    10000    40000   25000.0
38      General Skobelev   Handysize    10000    40000   25000.0
39            Stalingrad   Handysize    10000    40000   25000.0
40    Aleksandr Shemagin   Handysize    10000    40000   25000.0
41               Kayseri     Suezmax   120000   200000  160000.0
42            Aura Maris   Handysize    10000    40000   25000.0
43                 Konya     Suezmax   120000   200000  160000.0
44             Khankendi     Aframax    80000   110000   95000.0
45  Stanislav Govorukhin   Handysize    10000    40000   25000.0
46             Bm Flot-3   Handysize    10000    40000   25000.0
47           Sergey Lvov   Handysize    10000    40000   25000.0
48      Viktor Vasnetsov   Handysize    10000    40000   25000.0
49        Pavel Bryullov   Handysize    10000    40000   25000.0

In [10]:
#timeless values of voyages range
voyages_range = {
    'Handysize':(8,14),
    'Aframax':(5,8),
    'Suezmax':(4,7),
}
load_factor = 0.95
bbl_per_tone = 7.33

vesseles['voyages_min'] = vesseles['tanker_size'].map(lambda s:voyague_range[s][0])
vesseles['voyages_max'] = vesseles['tanker_size'].map(lambda s:voyague_range[s][1])

vesseles['tonnes_low'] = vesseles['dwt_min']*vesseles['voyages_min']*load_factor
vesseles['tonnes_high'] = vesseles['dwt_max']*vesseles['voyages_max']*load_factor

vesseles['bbl_low'] = vesseles['tonnes_low']*bbl_per_tone
vesseles['bbl_high'] = vesseles['tonnes_high']*load_factor

In [11]:
urals_price = 66.5

vesseles['value_low'] = vesseles['bbl_low']*urals_price
vesseles['value_high'] = vesseles['bbl_high']*urals_price

by_class = vesseles.groupby('tanker_size')[['value_low','value_high']].sum()

In [12]:
vesseles.head()

,imo,vessel_name,tanker_size,build_year,flag,ship_manager,registered_owner,ism_manager,list_source,dwt_min,dwt_max,dwt_mid,voyages_min,tonnes_low,voyages_max,tonnes_high,bbl_low,bbl_high,value_low,value_high
0,9328170,Aether,Aframax,2007,Unknown,UAE. Zulu Ships Management,UAE. Wrasse Ship Co,UAE. Zulu Ships Management,new_crude_2025,80000,110000,95000.0,5,380000.0,8,836000.0,2785400.0,794200.0,185229100.0,52814300.0
1,9282481,Tagor,Aframax,2005,Unknown,UAE. Zulu Ships Management,UAE. Blaire Charters Ltd,UAE. Tarabya Logistics Ltd,new_crude_2025,80000,110000,95000.0,5,380000.0,8,836000.0,2785400.0,794200.0,185229100.0,52814300.0
2,9236248,Phoenix I,Aframax,2002,Comoros,UAE. Triviality Shipping Llc,UAE. Celestial Overseas Co Ltd,UAE. Triviality Shipping Llc,new_crude_2025,80000,110000,95000.0,5,380000.0,8,836000.0,2785400.0,794200.0,185229100.0,52814300.0
3,9439383,Bhilva,Aframax,2010,Panama,Seychelles. Tika Shipping Ltd,Seychelles. Tika Shipping Ltd,China. Song Hua Jiang Shipmanagement,new_crude_2025,80000,110000,95000.0,5,380000.0,8,836000.0,2785400.0,794200.0,185229100.0,52814300.0
4,9311610,Torx,Suezmax,2006,Panama,Seychelles. Shiva Shipping Ltd,Seychelles. Shiva Shipping Ltd,Singapore. Crest Maritime Pte Ltd,new_crude_2025,120000,200000,160000.0,4,456000.0,7,1330000.0,3342480.0,1263500.0,222274920.0,84022750.0