In [68]:
%load_ext autoreload
%autoreload 2


import time
import os
import pandas as pd
import requests
from pprint import pprint

from utils import get_vessel_info, headers, get_vessels_ids, get_port_visitors, parse_port_visits
vesseles = pd.read_csv('../data/shadow_fleet_vessels.csv')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 1. Capacity (DWT ranges)

In [69]:
size_DWT = {
    'Handysize':(7000,40000), #The lower limit has been lowered because we are taking annual ships into account
    'Aframax':(80000,110000),
    'Suezmax':(120000,200000),
}
vesseles['dwt_min'] = vesseles['tanker_size'].map(lambda s:size_DWT[s][0])
vesseles['dwt_max'] = vesseles['tanker_size'].map(lambda s:size_DWT[s][1])
vesseles['dwt_mid'] = (vesseles['dwt_min'] + vesseles['dwt_max']) / 2

vesseles[['vessel_name','tanker_size', 'dwt_min','dwt_max', 'dwt_mid']]

             vessel_name tanker_size  dwt_min  dwt_max   dwt_mid
0                 Aether     Aframax    80000   110000   95000.0
1                  Tagor     Aframax    80000   110000   95000.0
2              Phoenix I     Aframax    80000   110000   95000.0
3                 Bhilva     Aframax    80000   110000   95000.0
4                   Torx     Suezmax   120000   200000  160000.0
5                 Aura 1     Aframax    80000   110000   95000.0
6                 Balu 6     Aframax    80000   110000   95000.0
7                  Jewel     Aframax    80000   110000   95000.0
8                Guanyin     Aframax    80000   110000   95000.0
9               Marjorie     Suezmax   120000   200000  160000.0
10                Tracos     Suezmax   120000   200000  160000.0
11             Ling Hong     Aframax    80000   110000   95000.0
12                 Samos     Suezmax   120000   200000  160000.0
13                  Bolu     Aframax    80000   110000   95000.0
14           Centurion I     Aframax    80000   110000   95000.0
15               Telesto     Aframax    80000   110000   95000.0
16                Alaric     Aframax    80000   110000   95000.0
17               Nilanga     Aframax    80000   110000   95000.0
18                Searun     Aframax    80000   110000   95000.0
19           Tiger Wings     Aframax    80000   110000   95000.0
20             Zhuo Yuan     Suezmax   120000   200000  160000.0
21               Tango 2     Aframax    80000   110000   95000.0
22               Tiger 6     Aframax    80000   110000   95000.0
23              Sara Sky     Aframax    80000   110000   95000.0
24               Oceanid     Aframax    80000   110000   95000.0
25              Ocean Ii     Suezmax   120000   200000  160000.0
26                Lachin   Handysize     7000    40000   23500.0
27                   Lxh     Suezmax   120000   200000  160000.0
28          Cc Innovator   Handysize     7000    40000   23500.0
29           As Calcutta   Handysize     7000    40000   23500.0
30               Jin Hui   Handysize     7000    40000   23500.0
31                  Zale     Suezmax   120000   200000  160000.0
32               Arktida   Handysize     7000    40000   23500.0
33        Vasily Surikov   Handysize     7000    40000   23500.0
34   Professor Malyshkin   Handysize     7000    40000   23500.0
35                 Thoth   Handysize     7000    40000   23500.0
36            Midvolga-3   Handysize     7000    40000   23500.0
37               Antares   Handysize     7000    40000   23500.0
38      General Skobelev   Handysize     7000    40000   23500.0
39            Stalingrad   Handysize     7000    40000   23500.0
40    Aleksandr Shemagin   Handysize     7000    40000   23500.0
41               Kayseri     Suezmax   120000   200000  160000.0
42            Aura Maris   Handysize     7000    40000   23500.0
43                 Konya     Suezmax   120000   200000  160000.0
44             Khankendi     Aframax    80000   110000   95000.0
45  Stanislav Govorukhin   Handysize     7000    40000   23500.0
46             Bm Flot-3   Handysize     7000    40000   23500.0
47           Sergey Lvov   Handysize     7000    40000   23500.0
48      Viktor Vasnetsov   Handysize     7000    40000   23500.0
49        Pavel Bryullov   Handysize     7000    40000   23500.0

In [70]:
#timeless values of voyages range
voyages_range = {
    'Handysize':(8,14),
    'Aframax':(5,8),
    'Suezmax':(4,7),
}
load_factor = 0.95
bbl_per_tone = 7.33

vesseles['voyages_min'] = vesseles['tanker_size'].map(lambda s:voyages_range[s][0])
vesseles['voyages_max'] = vesseles['tanker_size'].map(lambda s:voyages_range[s][1])

vesseles['tonnes_low'] = vesseles['dwt_min']*vesseles['voyages_min']*load_factor
vesseles['tonnes_high'] = vesseles['dwt_max']*vesseles['voyages_max']*load_factor

vesseles['bbl_low'] = vesseles['tonnes_low']*bbl_per_tone
vesseles['bbl_high'] = vesseles['tonnes_high']*bbl_per_tone

In [71]:
urals_price = 66.5

vesseles['value_low'] = vesseles['bbl_low']*urals_price
vesseles['value_high'] = vesseles['bbl_high']*urals_price

by_class = vesseles.groupby('tanker_size')[['value_low','value_high']].sum()

In [72]:
vesseles.head()

,imo,vessel_name,tanker_size,build_year,flag,ship_manager,registered_owner,ism_manager,list_source,dwt_min,dwt_max,dwt_mid,voyages_min,voyages_max,tonnes_low,tonnes_high,bbl_low,bbl_high,value_low,value_high
0,9328170,Aether,Aframax,2007,Unknown,UAE. Zulu Ships Management,UAE. Wrasse Ship Co,UAE. Zulu Ships Management,new_crude_2025,80000,110000,95000.0,5,8,380000.0,836000.0,2785400.0,6127880.0,185229100.0,407504020.0
1,9282481,Tagor,Aframax,2005,Unknown,UAE. Zulu Ships Management,UAE. Blaire Charters Ltd,UAE. Tarabya Logistics Ltd,new_crude_2025,80000,110000,95000.0,5,8,380000.0,836000.0,2785400.0,6127880.0,185229100.0,407504020.0
2,9236248,Phoenix I,Aframax,2002,Comoros,UAE. Triviality Shipping Llc,UAE. Celestial Overseas Co Ltd,UAE. Triviality Shipping Llc,new_crude_2025,80000,110000,95000.0,5,8,380000.0,836000.0,2785400.0,6127880.0,185229100.0,407504020.0
3,9439383,Bhilva,Aframax,2010,Panama,Seychelles. Tika Shipping Ltd,Seychelles. Tika Shipping Ltd,China. Song Hua Jiang Shipmanagement,new_crude_2025,80000,110000,95000.0,5,8,380000.0,836000.0,2785400.0,6127880.0,185229100.0,407504020.0
4,9311610,Torx,Suezmax,2006,Panama,Seychelles. Shiva Shipping Ltd,Seychelles. Shiva Shipping Ltd,Singapore. Crest Maritime Pte Ltd,new_crude_2025,120000,200000,160000.0,4,7,456000.0,1330000.0,3342480.0,9748900.0,222274920.0,648301850.0

## 3. Port visits (GFW)
for ship Tagor

In [73]:

from utils import get_vessel_info, headers

raw_test = get_vessel_info(9282481)
for entry in raw_test['entries']:
    for rec in entry['selfReportedInfo']:
        print(rec['id'],rec['shipname'])

c0830f34f-ff65-a8f1-62c9-1f0e4b069ae5 BRITISH GANNET
e343b1da5-5b7a-de04-e72f-279e95210584 TAGOR
3b359ae29-977a-8747-4fe7-0f0f79269db8 TAGOR
97776be53-3f32-2f42-0439-c5cb44cc945d TAGOR
1ff0ec2ce-ef7a-75f9-7c67-38abeb4f9207 PIPER
a4ab02c0f-f6ed-739d-2413-54991555104c FRENCH NAVY WARSHIP
20c2c5af0-044e-1a07-536f-ebe21ab350b3 PRIAPUS
779363393-3c4a-27ae-e75c-568791c59948 TAGOR

In [74]:
url = "https://gateway.api.globalfishingwatch.org/v3/events"
params = {
    'datasets[0]':'public-global-port-visits-events:latest',
    'vessels[0]': 'e343b1da5-5b7a-de04-e72f-279e95210584',
    'start-date': '2025-01-01',
    'end-date': '2025-12-31',
    'limit': 100,
    'offset': 0
}
r = requests.get(url, headers= headers, params=params )
print (r.text)

{"metadata":{"datasets":["public-global-port-visits-events:v4.0"],"vessels":["e343b1da5-5b7a-de04-e72f-279e95210584"],"dateRange":{"from":"2025-01-01","to":"2025-12-31"}},"limit":100,"offset":0,"nextOffset":null,"total":15,"entries":[{"start":"2024-12-14T05:37:40.000Z","end":"2025-01-03T09:41:13.000Z","id":"80f50b20892a3dcdbebc6cdb37e84c89","type":"port_visit","position":{"lat":59.9233,"lon":28.5965},"regions":{"mpa":[],"eez":["5690"],"rfmo":["NASCO","IWC","ICES","ACAP","ICCAT","NAMMCO"],"fao":["27.3","27","27.3.d","27.3.d.32"],"majorFao":["27"],"eez12Nm":["5690"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[28.59650657494041,59.92333973477929,28.600174237032302,59.91691358779298],"distances":{"startDistanceFromShoreKm":8,"endDistanceFromShoreKm":8,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"3422710371cc82a2819d128e8c31001d","confidence":"4","durationHrs":484.05916666666667,"startAnchorage":{"anchorageId":"46969731","atDock":false,"distanceFromShoreKm":"8","flag":"RUS","id":"rus-ustluga","lat":59.92333973477929,"lon":28.59650657494041,"name":null,"topDestination":"UST LUGA"},"intermediateAnchorage":{"anchorageId":"46969731","atDock":false,"distanceFromShoreKm":"8","flag":"RUS","id":"rus-ustluga","lat":59.92333973477929,"lon":28.59650657494041,"name":null,"topDestination":"UST LUGA"},"endAnchorage":{"anchorageId":"46969735","atDock":false,"distanceFromShoreKm":"8","flag":"RUS","id":"rus-ustluga","lat":59.91691358779298,"lon":28.600174237032302,"name":null,"topDestination":"UST LUGA"}}},{"start":"2025-01-04T21:50:35.000Z","end":"2025-01-06T02:11:44.000Z","id":"208cd3d532c260773d2c8cd010ca8c7c","type":"port_visit","position":{"lat":60.004,"lon":28.4941},"regions":{"mpa":[],"eez":["5690"],"rfmo":["ICES","NASCO","IWC","NAMMCO","ACAP","ICCAT"],"fao":["27.3","27","27.3.d","27.3.d.32"],"majorFao":["27"],"eez12Nm":["5690"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[28.494106235225114,60.00399118621962,28.498769809596048,60.02773763865024],"distances":{"startDistanceFromShoreKm":6,"endDistanceFromShoreKm":6,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"cf07e3a8db16f4551dbdd569db5aab71","confidence":"4","durationHrs":28.3525,"startAnchorage":{"anchorageId":"4696bdfb","atDock":false,"distanceFromShoreKm":"6","flag":"RUS","id":"rus-primorsk","lat":60.00399118621962,"lon":28.494106235225114,"name":null,"topDestination":"PRIMORSK"},"intermediateAnchorage":{"anchorageId":"4696bdfb","atDock":false,"distanceFromShoreKm":"6","flag":"RUS","id":"rus-primorsk","lat":60.00399118621962,"lon":28.494106235225114,"name":null,"topDestination":"PRIMORSK"},"endAnchorage":{"anchorageId":"4696be13","atDock":false,"distanceFromShoreKm":"6","flag":"RUS","id":"rus-primorsk","lat":60.02773763865024,"lon":28.498769809596048,"name":null,"topDestination":"PRIMORSK"}}},{"start":"2025-01-06T05:14:57.000Z","end":"2025-01-07T17:15:23.000Z","id":"266ed9aea90f1a6e829db8d2310bdc21","type":"port_visit","position":{"lat":60.3043,"lon":28.7486},"regions":{"mpa":[],"eez":["5690"],"rfmo":["ICES","ACAP","ICCAT","NAMMCO","NASCO","IWC"],"fao":["27.3","27","27.3.d.32","27.3.d"],"majorFao":["27"],"eez12Nm":["5690"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[28.748639395345986,60.304309641312,28.748639395345986,60.304309641312],"distances":{"startDistanceFromShoreKm":2,"endDistanceFromShoreKm":2,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"55da0acc5d3cae965bef54f340bee63f","confidence":"4","durationHrs":36.007222222222225,"startAnchorage":{"anchorageId":"4696dcf5","atDock":false,"distanceFromShoreKm":"2","flag":"RUS","id":"rus-primorsk","lat":60.304309641312,"lon":28.748639395345986,"name":null,"topDestination":"PRIMORSK"},"intermediateAnchorage":{"anchorageId":"4696dcf5","atDock":false,"distanceFromShoreKm":"2","flag":"RUS","id":"rus-primorsk","lat":60.304309641312,"lon":28.748639395345986,"name":null,"topDestination":"PRIMORSK"},"endAnchorage":{"anchorageId":"4696dcf5","atDock":false,"distanceFromShoreKm":"2","flag":"RUS","id":"rus-primorsk","lat":60.304309641312,"lon":28.748639395345986,"name":null,"topDestination":"PRIMORSK"}}},{"start":"2025-01-11T23:48:06.000Z","end":"2025-01-12T07:59:45.000Z","id":"78b2bd74a298be2d8b41646ad6e98051","type":"port_visit","position":{"lat":57.6747,"lon":10.7227},"regions":{"mpa":[],"eez":["5674"],"rfmo":["ICES","ACAP","NEAFC","NASCO","ICCAT","IWC","NAMMCO"],"fao":["27.3.a","27","27.3.a.21","27.3"],"majorFao":["27"],"eez12Nm":["5674"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[10.722731808588588,57.67465352468821,10.718633779515038,57.68717311779676],"distances":{"startDistanceFromShoreKm":9,"endDistanceFromShoreKm":7,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"819791d54f3b94fbd6ad845ca552edce","confidence":"4","durationHrs":8.194166666666666,"startAnchorage":{"anchorageId":"464f424f","atDock":false,"distanceFromShoreKm":"9","flag":"DNK","id":"dnk-skagen","lat":57.67465352468821,"lon":10.722731808588588,"name":"SKAGEN","topDestination":"SKAGEN"},"intermediateAnchorage":{"anchorageId":"464f424f","atDock":false,"distanceFromShoreKm":"9","flag":"DNK","id":"dnk-skagen","lat":57.67465352468821,"lon":10.722731808588588,"name":"SKAGEN","topDestination":"SKAGEN"},"endAnchorage":{"anchorageId":"464f4255","atDock":false,"distanceFromShoreKm":"7","flag":"DNK","id":"dnk-skagen","lat":57.68717311779676,"lon":10.718633779515038,"name":"SKAGEN","topDestination":"SKAGEN"}}},{"start":"2025-02-03T10:37:37.000Z","end":"2025-02-04T03:38:15.000Z","id":"31e21c7fa2903d49e5dc08243601b1ba","type":"port_visit","position":{"lat":31.4718,"lon":32.3028},"regions":{"mpa":[],"eez":["8490"],"rfmo":["GFCM","ACAP","IWC","ICCAT"],"fao":["37","37.3.2","37.3"],"majorFao":["37"],"eez12Nm":["8490"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[32.30275693031122,31.471754569476413,32.33520754777416,31.472745013183648],"distances":{"startDistanceFromShoreKm":21,"endDistanceFromShoreKm":21,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"9a422c1c80bcc2c5da68f1702094e2d7","confidence":"4","durationHrs":17.010555555555555,"startAnchorage":{"anchorageId":"14f98083","atDock":false,"distanceFromShoreKm":"21","flag":"EGY","id":"egy-portsaid","lat":31.471754569476413,"lon":32.30275693031122,"name":"PORT SAID","topDestination":"PORT SAID"},"intermediateAnchorage":{"anchorageId":"14f98083","atDock":false,"distanceFromShoreKm":"21","flag":"EGY","id":"egy-portsaid","lat":31.471754569476413,"lon":32.30275693031122,"name":"PORT SAID","topDestination":"PORT SAID"},"endAnchorage":{"anchorageId":"14fa2aa3","atDock":false,"distanceFromShoreKm":"21","flag":"EGY","id":"egy-portsaid","lat":31.472745013183648,"lon":32.33520754777416,"name":"PORT SAID","topDestination":"PORT SAID"}}},{"start":"2025-02-15T16:15:21.000Z","end":"2025-02-20T10:37:42.000Z","id":"63ae62604481f37f0528863d607bf9af","type":"port_visit","position":{"lat":22.6357,"lon":69.6243},"regions":{"mpa":[],"eez":["8480"],"rfmo":["IOTC","ACAP","IWC"],"fao":["51","51.4"],"majorFao":["51"],"eez12Nm":[],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[69.62425498554863,22.635652617309294,69.54722396608886,22.659203880695337],"distances":{"startDistanceFromShoreKm":13,"endDistanceFromShoreKm":12,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"69d66528ffd90ace325ad682f8ee244f","confidence":"4","durationHrs":114.3725,"startAnchorage":{"anchorageId":"3956d7a1","atDock":false,"distanceFromShoreKm":"13","flag":"IND","id":"ind-mundra","lat":22.635652617309294,"lon":69.62425498554863,"name":null,"topDestination":"MUNDRA"},"intermediateAnchorage":{"anchorageId":"3956d7a1","atDock":false,"distanceFromShoreKm":"13","flag":"IND","id":"ind-mundra","lat":22.635652617309294,"lon":69.62425498554863,"name":null,"topDestination":"MUNDRA"},"endAnchorage":{"anchorageId":"3956d117","atDock":false,"distanceFromShoreKm":"12","flag":"IND","id":"ind-mundra","lat":22.659203880695337,"lon":69.54722396608886,"name":null,"topDestination":"MUNDRA"}}},{"start":"2025-02-25T09:30:25.000Z","end":"2025-03-05T19:40:49.000Z","id":"e81a284672ec951e5feb791a14d29671","type":"port_visit","position":{"lat":25.3985,"lon":56.5971},"regions":{"mpa":[],"eez":["8360"],"rfmo":["IOTC","ACAP","IWC","RECOFI"],"fao":["51","51.3"],"majorFao":["51"],"eez12Nm":[],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[56.597101413521905,25.398533706792296,56.597278515340356,25.388907457884326],"distances":{"startDistanceFromShoreKm":23,"endDistanceFromShoreKm":23,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"c8bd8ca75f12d299ff4e5513a02710a4","confidence":"4","durationHrs":202.17333333333335,"startAnchorage":{"anchorageId":"3ef4685d","atDock":false,"distanceFromShoreKm":"23","flag":"ARE","id":"are-khorfakkan","lat":25.398533706792296,"lon":56.597101413521905,"name":"KHOR FAKKAN","topDestination":"FUJAIRAH"},"intermediateAnchorage":{"anchorageId":"3ef4685d","atDock":false,"distanceFromShoreKm":"23","flag":"ARE","id":"are-khorfakkan","lat":25.398533706792296,"lon":56.597101413521905,"name":"KHOR FAKKAN","topDestination":"FUJAIRAH"},"endAnchorage":{"anchorageId":"3ef46865","atDock":false,"distanceFromShoreKm":"23","flag":"ARE","id":"are-khorfakkan","lat":25.388907457884326,"lon":56.597278515340356,"name":"KHOR FAKKAN","topDestination":"FUJAIRAH"}}},{"start":"2025-03-08T11:07:23.000Z","end":"2025-04-07T00:28:38.000Z","id":"a94c24d5d2d4af5b9767eb13cbf3cf00","type":"port_visit","position":{"lat":19.6832,"lon":57.7259},"regions":{"mpa":["555760583"],"eez":["8354"],"rfmo":["RECOFI","IOTC","ACAP","IWC"],"fao":["51","51.3"],"majorFao":["51"],"eez12Nm":["8354"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[57.72590681723144,19.6832035356171,57.72590681723144,19.6832035356171],"distances":{"startDistanceFromShoreKm":3,"endDistanceFromShoreKm":3,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"f9d5bd139f8e8a465382855413b0e4a1","confidence":"4","durationHrs":709.3541666666666,"startAnchorage":{"anchorageId":"3e828b8d","atDock":false,"distanceFromShoreKm":"3","flag":"OMN","id":"omn-duqm","lat":19.6832035356171,"lon":57.72590681723144,"name":"DUQM","topDestination":"AL DUQUM OMAN"},"intermediateAnchorage":{"anchorageId":"3e828b8d","atDock":false,"distanceFromShoreKm":"3","flag":"OMN","id":"omn-duqm","lat":19.6832035356171,"lon":57.72590681723144,"name":"DUQM","topDestination":"AL DUQUM OMAN"},"endAnchorage":{"anchorageId":"3e828b8d","atDock":false,"distanceFromShoreKm":"3","flag":"OMN","id":"omn-duqm","lat":19.6832035356171,"lon":57.72590681723144,"name":"DUQM","topDestination":"AL DUQUM OMAN"}}},{"start":"2025-04-15T22:58:43.000Z","end":"2025-04-17T06:42:29.000Z","id":"29f575e8e825f7cfa0e8fc793889e4f9","type":"port_visit","position":{"lat":29.7248,"lon":32.5846},"regions":{"mpa":[],"eez":["8490"],"rfmo":["IOTC","PERSGA","IWC","ACAP"],"fao":["51","51.1"],"majorFao":["51"],"eez12Nm":[],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[32.5846331831365,29.724772532969432,32.57345146756374,29.947923995215316],"distances":{"startDistanceFromShoreKm":9,"endDistanceFromShoreKm":0,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"6a2f70e3d691027ac572d86c0ec1ecc6","confidence":"4","durationHrs":31.729444444444443,"startAnchorage":{"anchorageId":"14564709","atDock":false,"distanceFromShoreKm":"9","flag":"EGY","id":"egy-suezsouthanchorage","lat":29.724772532969432,"lon":32.5846331831365,"name":"SUEZ SOUTH ANCHORAGE","topDestination":"SUEZ"},"intermediateAnchorage":{"anchorageId":"14564709","atDock":false,"distanceFromShoreKm":"9","flag":"EGY","id":"egy-suezsouthanchorage","lat":29.724772532969432,"lon":32.5846331831365,"name":"SUEZ SOUTH ANCHORAGE","topDestination":"SUEZ"},"endAnchorage":{"anchorageId":"1456251b","atDock":true,"distanceFromShoreKm":"0","flag":"EGY","id":"egy-suezport","lat":29.947923995215316,"lon":32.57345146756374,"name":"SUEZ PORT","topDestination":"ATHENES"}}},{"start":"2025-04-30T14:52:31.000Z","end":"2025-05-01T06:11:18.000Z","id":"a41b6200e6538a7133c2bd9a5e3f1c05","type":"port_visit","position":{"lat":57.6747,"lon":10.7227},"regions":{"mpa":[],"eez":["5674"],"rfmo":["ICES","NAMMCO","NEAFC","ACAP","NASCO","ICCAT","IWC"],"fao":["27.3","27","27.3.a.21","27.3.a"],"majorFao":["27"],"eez12Nm":["5674"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[10.722731808588588,57.67465352468821,10.722731808588588,57.67465352468821],"distances":{"startDistanceFromShoreKm":9,"endDistanceFromShoreKm":9,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"a11e270cbdda4b777437e07ac22e74d0","confidence":"4","durationHrs":15.313055555555556,"startAnchorage":{"anchorageId":"464f424f","atDock":false,"distanceFromShoreKm":"9","flag":"DNK","id":"dnk-skagen","lat":57.67465352468821,"lon":10.722731808588588,"name":"SKAGEN","topDestination":"SKAGEN"},"intermediateAnchorage":{"anchorageId":"464f424f","atDock":false,"distanceFromShoreKm":"9","flag":"DNK","id":"dnk-skagen","lat":57.67465352468821,"lon":10.722731808588588,"name":"SKAGEN","topDestination":"SKAGEN"},"endAnchorage":{"anchorageId":"464f424f","atDock":false,"distanceFromShoreKm":"9","flag":"DNK","id":"dnk-skagen","lat":57.67465352468821,"lon":10.722731808588588,"name":"SKAGEN","topDestination":"SKAGEN"}}},{"start":"2025-05-15T09:55:00.000Z","end":"2025-05-17T10:48:28.000Z","id":"ce74efe882eaec834725fc4b72f5fec5","type":"port_visit","position":{"lat":59.7829,"lon":28.4077},"regions":{"mpa":[],"eez":["5690"],"rfmo":["ICES","IWC","ICCAT","NAMMCO","ACAP","NASCO"],"fao":["27.3.d.32","27.3","27.3.d","27"],"majorFao":["27"],"eez12Nm":["5690"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[28.40772420992392,59.78286384398603,28.444391931179812,59.7849305238738],"distances":{"startDistanceFromShoreKm":1,"endDistanceFromShoreKm":0,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"485996f31e89721ca8a7cfb5b2550416","confidence":"4","durationHrs":48.89111111111111,"startAnchorage":{"anchorageId":"46969e89","atDock":false,"distanceFromShoreKm":"1","flag":"RUS","id":"rus-vistino","lat":59.78286384398603,"lon":28.40772420992392,"name":"VISTINO","topDestination":"UST LUGA"},"intermediateAnchorage":{"anchorageId":"46969e89","atDock":false,"distanceFromShoreKm":"1","flag":"RUS","id":"rus-vistino","lat":59.78286384398603,"lon":28.40772420992392,"name":"VISTINO","topDestination":"UST LUGA"},"endAnchorage":{"anchorageId":"46969c29","atDock":true,"distanceFromShoreKm":"0","flag":"RUS","id":"rus-vistino","lat":59.7849305238738,"lon":28.444391931179812,"name":"VISTINO","topDestination":"UST LUGA"}}},{"start":"2025-06-04T10:18:57.000Z","end":"2025-06-05T03:20:55.000Z","id":"3871d8935ddf982edfddb83e475d42ec","type":"port_visit","position":{"lat":31.4718,"lon":32.3028},"regions":{"mpa":[],"eez":["8490"],"rfmo":["ACAP","ICCAT","GFCM","IWC"],"fao":["37.3.2","37.3","37"],"majorFao":["37"],"eez12Nm":["8490"],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[32.30275693031122,31.471754569476413,32.33507202609875,31.457928800214084],"distances":{"startDistanceFromShoreKm":21,"endDistanceFromShoreKm":20,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"a27745fc6aeed5a41a1e9c6eb6bc65ff","confidence":"4","durationHrs":17.032777777777778,"startAnchorage":{"anchorageId":"14f98083","atDock":false,"distanceFromShoreKm":"21","flag":"EGY","id":"egy-portsaid","lat":31.471754569476413,"lon":32.30275693031122,"name":"PORT SAID","topDestination":"PORT SAID"},"intermediateAnchorage":{"anchorageId":"14f98083","atDock":false,"distanceFromShoreKm":"21","flag":"EGY","id":"egy-portsaid","lat":31.471754569476413,"lon":32.30275693031122,"name":"PORT SAID","topDestination":"PORT SAID"},"endAnchorage":{"anchorageId":"14f9800d","atDock":false,"distanceFromShoreKm":"20","flag":"EGY","id":"egy-portsaid","lat":31.457928800214084,"lon":32.33507202609875,"name":"PORT SAID","topDestination":"PORT SAID"}}},{"start":"2025-06-05T14:05:05.000Z","end":"2025-06-08T20:30:00.000Z","id":"31acff1f36233317d2248dd6cae89ad1","type":"port_visit","position":{"lat":29.9479,"lon":32.5735},"regions":{"mpa":[],"eez":["8490"],"rfmo":["ACAP","IOTC","PERSGA","IWC"],"fao":["51","51.1"],"majorFao":["51"],"eez12Nm":[],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[32.57345146756374,29.947923995215316,32.55851489116695,29.7883876749519],"distances":{"startDistanceFromShoreKm":0,"endDistanceFromShoreKm":6,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visit":{"visitId":"a0fe1242f6ae7d1cf53621ab3773b3ee","confidence":"4","durationHrs":78.41527777777777,"startAnchorage":{"anchorageId":"1456251b","atDock":true,"distanceFromShoreKm":"0","flag":"EGY","id":"egy-suezport","lat":29.947923995215316,"lon":32.57345146756374,"name":"SUEZ PORT","topDestination":"ATHENES"},"intermediateAnchorage":{"anchorageId":"1456251b","atDock":true,"distanceFromShoreKm":"0","flag":"EGY","id":"egy-suezport","lat":29.947923995215316,"lon":32.57345146756374,"name":"SUEZ PORT","topDestination":"ATHENES"},"endAnchorage":{"anchorageId":"14563839","atDock":false,"distanceFromShoreKm":"6","flag":"EGY","id":"egy-suezsouthanchorage","lat":29.7883876749519,"lon":32.55851489116695,"name":"SUEZ SOUTH ANCHORAGE","topDestination":"SUEZ"}}},{"start":"2025-07-04T18:15:32.000Z","end":"2025-07-07T10:45:07.000Z","id":"0d47d53dbe24b8570b2d738c058775ab","type":"port_visit","position":{"lat":29.7022,"lon":122.6307},"regions":{"mpa":[],"eez":["8486"],"rfmo":["APFIC","ACAP","WCPFC","IWC"],"fao":["61"],"majorFao":["61"],"eez12Nm":[],"highSeas":[],"mpaNoTakePartial":[],"mpaNoTake":[]},"boundingBox":[122.63069047048799,29.702235309396222,122.51133222258048,29.713755664582894],"distances":{"startDistanceFromShoreKm":27,"endDistanceFromShoreKm":18,"startDistanceFromPortKm":0,"endDistanceFromPortKm":0},"vessel":{"id":"e343b1da5-5b7a-de04-e72f-279e95210584","name":"TAGOR","ssvid":"352002249","flag":"PAN","type":"other","nextPort":null},"port_visi

In [75]:
data = r.json()
first=data['entries'][0]

first.keys()

dict_keys(['start', 'end', 'id', 'type', 'position', 'regions', 'boundingBox', 'distances', 'vessel', 'port_visit'])

In [76]:


pprint(first['port_visit'])

{'confidence': '4',
 'durationHrs': 484.05916666666667,
 'endAnchorage': {'anchorageId': '46969735',
                  'atDock': False,
                  'distanceFromShoreKm': '8',
                  'flag': 'RUS',
                  'id': 'rus-ustluga',
                  'lat': 59.91691358779298,
                  'lon': 28.600174237032302,
                  'name': None,
                  'topDestination': 'UST LUGA'},
 'intermediateAnchorage': {'anchorageId': '46969731',
                           'atDock': False,
                           'distanceFromShoreKm': '8',
                           'flag': 'RUS',
                           'id': 'rus-ustluga',
                           'lat': 59.92333973477929,
                           'lon': 28.59650657494041,
                           'name': None,
                           'topDestination': 'UST LUGA'},
 'startAnchorage': {'anchorageId': '46969731',
                    'atDock': False,
                    'distanceFromShoreKm': '8',
                    'flag': 'RUS',
                    'id': 'rus-ustluga',
                    'lat': 59.92333973477929,
                    'lon': 28.59650657494041,
                    'name': None,
                    'topDestination': 'UST LUGA'},
 'visitId': '3422710371cc82a2819d128e8c31001d'}

In [77]:
rows = []
for e in data ['entries']:
    anch = e['port_visit']['intermediateAnchorage']
    rows.append({
        'start': e['start'],
        'port': anch['topDestination'],
        'country': anch['flag'],
        'hours':e['port_visit']['durationHrs'],
        'at_dock': anch['atDock']
    })

visits = pd.DataFrame(rows)
visits

# Rough tanker port-stay heuristics (hours):
# <6    short stop (crew, supplies, pilot)
# 6-24  canal transit / bunkering
# 24-48 loading or discharge at berth
# 48-120 discharge + queue / STS transfer
# 120-360 waiting for orders / floating storage
# >360  repair / drydock / long idle

                       start           port country       hours  at_dock
0   2024-12-14T05:37:40.000Z       UST LUGA     RUS  484.059167    False
1   2025-01-04T21:50:35.000Z       PRIMORSK     RUS   28.352500    False
2   2025-01-06T05:14:57.000Z       PRIMORSK     RUS   36.007222    False
3   2025-01-11T23:48:06.000Z         SKAGEN     DNK    8.194167    False
4   2025-02-03T10:37:37.000Z      PORT SAID     EGY   17.010556    False
5   2025-02-15T16:15:21.000Z         MUNDRA     IND  114.372500    False
6   2025-02-25T09:30:25.000Z       FUJAIRAH     ARE  202.173333    False
7   2025-03-08T11:07:23.000Z  AL DUQUM OMAN     OMN  709.354167    False
8   2025-04-15T22:58:43.000Z           SUEZ     EGY   31.729444    False
9   2025-04-30T14:52:31.000Z         SKAGEN     DNK   15.313056    False
10  2025-05-15T09:55:00.000Z       UST LUGA     RUS   48.891111    False
11  2025-06-04T10:18:57.000Z      PORT SAID     EGY   17.032778    False
12  2025-06-05T14:05:05.000Z        ATHENES     EGY   78.415278     True
13  2025-07-04T18:15:32.000Z         NINGBO     CHN   64.493056    False
14  2025-07-27T15:25:41.000Z        KOZMINO     RUS   40.325833    False

### Can `atDock` identify loadings?
No. `atDock` is `False` for all RUS port visits of Tagor, including Russian oil terminals
where the vessel must have loaded. The flag is not reliable in GFW data, so it is not used.

**How loadings are identified instead:**
- port country = `RUS`
- stay of roughly 24–48 hours (typical loading time for an Aframax)
- consecutive visits to the same port are counted as one loading (e.g. Primorsk, 4 and 6 Jan)

In [78]:
ru = visits[visits['country'] == 'RUS'].drop(columns=['at_dock'])
loadings = ru[(ru['hours'] >= 12) & (ru['hours'] <= 120)]
loadings = loadings[loadings['port']!=loadings['port'].shift()]
loadings

                       start      port country      hours
1   2025-01-04T21:50:35.000Z  PRIMORSK     RUS  28.352500
10  2025-05-15T09:55:00.000Z  UST LUGA     RUS  48.891111
14  2025-07-27T15:25:41.000Z   KOZMINO     RUS  40.325833

Tagor: **3 loadings** in 2025 (Primorsk ×2 visits = 1 loading).

In [79]:
len(loadings)

3

In [80]:
n_loadings = len(loadings)
tagor = vesseles[vesseles['vessel_name']=='Tagor'].iloc[0]

real_low = n_loadings*tagor['dwt_min']*load_factor*bbl_per_tone*urals_price
real_high =n_loadings*tagor['dwt_max']*load_factor*bbl_per_tone*urals_price

print(real_low/1e6, real_high/1e6)

111.13746 152.8140075

### Tagor: real loadings vs assumption
| | Loadings | Cargo value |
|---|---|---|
| Assumption (section 2) | 5–8 / year | $185–408M |
| GFW port visits | 3 in ~7 months (≈5 / year) | **$111–153M** |

The assumption was reasonable, but on the high side.

This is a **lower bound**:
- data ends on 27 Jul (AIS could be off after that)
- only 1 of Tagor's 8 GFW ids was used
- the 20-day Ust-Luga stay was not counted (possible STS)

In [81]:
#chek def get_port_visitors and parse_port_visitors for ship TAGOR
get_vessels_ids(9282481)

['c0830f34f-ff65-a8f1-62c9-1f0e4b069ae5',
 'e343b1da5-5b7a-de04-e72f-279e95210584',
 '3b359ae29-977a-8747-4fe7-0f0f79269db8',
 '97776be53-3f32-2f42-0439-c5cb44cc945d',
 '1ff0ec2ce-ef7a-75f9-7c67-38abeb4f9207',
 'a4ab02c0f-f6ed-739d-2413-54991555104c',
 '20c2c5af0-044e-1a07-536f-ebe21ab350b3',
 '779363393-3c4a-27ae-e75c-568791c59948']

In [82]:
ids = get_vessels_ids(9282481)
entries = get_port_visitors(ids)
len(entries)

16

In [83]:
rows = parse_port_visits(9282481, entries)
tagor_all = pd.DataFrame(rows).sort_values('start')
tagor_all

        imo                     start           port country       hours
0   9282481  2024-12-14T05:37:40.000Z       UST LUGA     RUS  484.059167
1   9282481  2025-01-04T21:50:35.000Z       PRIMORSK     RUS   28.352500
2   9282481  2025-01-06T05:14:57.000Z       PRIMORSK     RUS   36.007222
3   9282481  2025-01-11T23:48:06.000Z         SKAGEN     DNK    8.194167
4   9282481  2025-02-03T10:37:37.000Z      PORT SAID     EGY   17.010556
5   9282481  2025-02-15T16:15:21.000Z         MUNDRA     IND  114.372500
6   9282481  2025-02-25T09:30:25.000Z       FUJAIRAH     ARE  202.173333
7   9282481  2025-03-08T11:07:23.000Z  AL DUQUM OMAN     OMN  709.354167
8   9282481  2025-04-15T22:58:43.000Z           SUEZ     EGY   31.729444
9   9282481  2025-04-30T14:52:31.000Z         SKAGEN     DNK   15.313056
10  9282481  2025-05-15T09:55:00.000Z       UST LUGA     RUS   48.891111
11  9282481  2025-06-04T10:18:57.000Z      PORT SAID     EGY   17.032778
12  9282481  2025-06-05T14:05:05.000Z        ATHENES     EGY   78.415278
13  9282481  2025-07-04T18:15:32.000Z         NINGBO     CHN   64.493056
14  9282481  2025-07-27T15:25:41.000Z        KOZMINO     RUS   40.325833
15  9282481  2025-11-06T07:06:37.000Z           SUEZ     EGY  167.548611

In [84]:

PATH = '../data/port-visits.csv'
if os.path.exists(PATH):
    port_visits = pd.read_csv(PATH)
else:
    all_rows = []
    for imo in vesseles['imo']:
        ids = get_vessels_ids(imo)
        entries = get_port_visitors(ids)
        all_rows.extend(parse_port_visits(imo, entries))
        time.sleep(0.5)

    port_visits = pd.DataFrame(all_rows)
    port_visits.to_csv(PATH, index=False)

port_visits.shape

(1755, 5)

In [85]:
#how many ships were in russia port
ru_all = port_visits[port_visits['country']=='RUS']
loadings_all = ru_all[(ru_all['hours']>=12)&(ru_all['hours']<=120)]
loadings_all = loadings_all.sort_values(['imo', 'start'])
loadings_all = loadings_all[loadings_all['port']!=loadings_all.groupby('imo')['port'].shift()]
loadings_all

          imo                     start         port country      hours
915   9037123  2025-05-19T11:53:27.000Z      KOZMINO     RUS  76.063056
925   9037123  2025-08-22T21:04:55.000Z       VANINO     RUS  79.505556
930   9037123  2025-10-25T22:50:47.000Z       RU VNN     RUS  53.876389
1246  9046564  2025-01-03T06:02:43.000Z  OKHOTSK SEA     RUS  80.398056
1251  9046564  2025-02-23T00:20:05.000Z    SLAVYANKA     RUS  38.223611
...       ...                       ...          ...     ...        ...
1622  9884150  2025-09-01T17:17:16.000Z        YEISK     RUS  54.613889
1627  9884150  2025-09-21T11:49:57.000Z       KAVKAZ     RUS  18.052500
1631  9884150  2025-10-09T11:02:59.000Z        KERCH     RUS  22.727222
1637  9884150  2025-11-07T07:49:02.000Z       KAVKAZ     RUS  43.660556
1642  9884150  2025-12-01T06:25:39.000Z        YEISK     RUS  58.156944

[310 rows x 5 columns]

In [91]:
n_load = loadings_all.groupby('imo').size().rename('n_loadings')
money = vesseles.merge(n_load, on='imo', how='left')
# River-sea shuttles: each round trip = 2 Russian port visits → count half
is_handy = money['tanker_size'] == "Handysize"
money.loc[is_handy, 'n_loadings'] = money.loc[is_handy, 'n_loadings'] / 2
money['n_loadings'] = money['n_loadings'].fillna(0)

money[['vessel_name', 'tanker_size', 'n_loadings']].sort_values('n_loadings', ascending=False)

             vessel_name tanker_size  n_loadings
35                 Thoth   Handysize        25.5
33        Vasily Surikov   Handysize        16.5
47           Sergey Lvov   Handysize        10.0
46             Bm Flot-3   Handysize         9.0
37               Antares   Handysize         9.0
36            Midvolga-3   Handysize         7.0
14           Centurion I     Aframax         7.0
34   Professor Malyshkin   Handysize         6.5
48      Viktor Vasnetsov   Handysize         5.5
49        Pavel Bryullov   Handysize         5.5
45  Stanislav Govorukhin   Handysize         5.0
17               Nilanga     Aframax         4.0
13                  Bolu     Aframax         4.0
4                   Torx     Suezmax         4.0
7                  Jewel     Aframax         4.0
31                  Zale     Suezmax         4.0
8                Guanyin     Aframax         4.0
3                 Bhilva     Aframax         4.0
18                Searun     Aframax         4.0
42            Aura Maris   Handysize         3.5
44             Khankendi     Aframax         3.0
20             Zhuo Yuan     Suezmax         3.0
23              Sara Sky     Aframax         3.0
24               Oceanid     Aframax         3.0
11             Ling Hong     Aframax         3.0
9               Marjorie     Suezmax         3.0
6                 Balu 6     Aframax         3.0
12                 Samos     Suezmax         3.0
1                  Tagor     Aframax         3.0
19           Tiger Wings     Aframax         3.0
25              Ocean Ii     Suezmax         3.0
30               Jin Hui   Handysize         2.5
5                 Aura 1     Aframax         2.0
0                 Aether     Aframax         2.0
26                Lachin   Handysize         2.0
27                   Lxh     Suezmax         2.0
16                Alaric     Aframax         2.0
2              Phoenix I     Aframax         2.0
22               Tiger 6     Aframax         2.0
29           As Calcutta   Handysize         1.5
43                 Konya     Suezmax         1.0
28          Cc Innovator   Handysize         1.0
21               Tango 2     Aframax         1.0
41               Kayseri     Suezmax         1.0
38      General Skobelev   Handysize         0.5
40    Aleksandr Shemagin   Handysize         0.5
39            Stalingrad   Handysize         0.5
10                Tracos     Suezmax         0.0
15               Telesto     Aframax         0.0
32               Arktida   Handysize         0.0

Handysize tankers (mostly river-sea) shuttle between two Russian ports
(e.g. Thoth: St Petersburg ↔ Ust-Luga), so each round trip shows up as 2 visits.
Their loadings are divided by 2.

In [94]:
money['real_low'] = money['n_loadings']*money['dwt_min']*load_factor*bbl_per_tone*urals_price
money['real_high'] = money['n_loadings']*money['dwt_max']*load_factor*bbl_per_tone*urals_price

print(money[['real_low', 'real_high']].sum() / 1e9)
money.groupby('tanker_size')[['n_loadings','real_low','real_high']].sum()

by_class_real = money.groupby('tanker_size')[['n_loadings', 'real_low', 'real_high']].sum()
by_class_real[['real_low', 'real_high']] = (by_class_real[['real_low', 'real_high']] / 1e9).round(2)
by_class_real
#real_low and realy_high show in bln usd

real_low     4.028964
real_high    7.497148
dtype: float64

             n_loadings  real_low  real_high
tanker_size
Aframax            63.0      2.33       3.21
Handysize         111.5      0.36       2.07
Suezmax            24.0      1.33       2.22

In [98]:
(money[['real_low', 'real_high']].sum() / 1e9).round(2)

real_low     4.03
real_high    7.50
dtype: float64